### ISSUE TITLE
Existing app name not found

### ISSUE THREAD

**Issue by MrHubble** [Microsoft/fastlane-plugin-mobile_center#2]
Even though I enter the correct app name in my fastfile, when I run `fastlane beta` I see:

````
[15:18:32]: App with name myappname not found, create one? (y/n)
y
[15:18:36]: Select OS
1. Android
2. iOS
?  2
[15:18:39]: Select Platform
1. Objective-C-Swift
2. React-Native
3. Xamarin
?  2
[15:18:42]: Error creating app 409: {"error"=>{"code"=>"Conflict", "message"=>"Validation error"}}
````

Does the `conflict` error suggest that the app is not created by an app by that name already exists?

**Comment by evkhramkov** [comment]
Hello @MrHubble! Sorry for delay.
Please, check `owner_name` in your Fastfile

**Comment by MrHubble** [comment]
ah, the `owner_name` is my Mobile Center account name (nothing to do with my developer credentials). That makes complete sense. It works when I correct the `owner_name`. Thanks for the help.

**Comment by temitopebello** [comment]
@MrHubble I am still wondering why fastlane created the app under my username instead of my Mobile center account name? Anyone knows why?
