### ISSUE TITLE
Feature request: support app names with spaces

### ISSUE THREAD

**Issue by JanBrinker** [Microsoft/fastlane-plugin-mobile_center#4]
I'm currently facing the issue that it seems like this plugin does not support spaces in the app name.

If I try to upload the app with a space in the name I get the following error message from fastlane:
> bad URI(is not URI?): /v0.1/apps/CompanyName/My Awesome App

If I go ahead and URI encode all the spaces I end up with the message
> App with name My%20Awesome%20App not found, create one? (y/n)

However in Mobile Center we already have set up the app "My Awesome App". It seems like the plugin does not URI decode the %20s back to spaces when neccessary.

Would love to have this supported :)

**Comment by evkhramkov** [comment]
In this plugin we are using the app slug, not the actual app name. If you open your “My Awesome App” in Mobile Center portal you will see something like `https://mobile.azure.com/users/CompanyName/apps/my-awesome-app` 
in the url, where `my-awesome-app` is the app slug which you should use in the plugin.

**Comment by JanBrinker** [comment]
Ah! Then it would be nice to have this reflected in the docs :)

Thanks for the help!

**Comment by iarpits** [comment]
But its a little misleading for the users. On install page, it shows `my-awesome-app` as the title but on iPhone the `App Display Name is `My Awesome App`. It would be better if you allow spaces in "app_name" because app center dashboard allows you to do that.
